# Generated by Django 4.2.26 on 2025-12-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('age_category', models.PositiveSmallIntegerField()),
                ('cinema_photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
