# Generated by Django 4.2.26 on 2026-01-21 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=700)),
                ('country', models.CharField(max_length=50)),
                ('photo_car_detail', models.ImageField(upload_to='')),
                ('is_stock', models.BooleanField(default=True)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.car')),
            ],
        ),
    ]
